from algorithms.dox_algorithm_adapter import *


def temp_callback(data):
    print(data)

if __name__ == "__main__":

    cases = [
        'C# is a prettyu cool language with LINQ support and such. XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\nPm id like smart grid demo ported spring" is a user story, and is worth 8 story points. This was predicted because it is most similar to: \n User id like option write file roll sink store local file system and similar to "Continuation would like investigate spark develop poc identify best appropriate design implementation" and similar to "Developer id like job module job shut complete instead current behavior context module regardless used achieve better resource utilization" (which are all user stories with a worth of 8 story points).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\nFix verification shell result table specific index use verification shell command table row specific row mostly first row like string id possible list table may intended row different order inconsistent test" is a user story, and is worth 3 story points. This was predicted because it is most similar to: \n Performance tester id like rerun baseline rabbit compare previous performance note - true - default could also vary default size compute record granular level and similar to "User id like option sink use provide better resiliency case willing accept performance penalty choose option" and similar to "Developer id like option source module consume data bandwidth efficient protocol fits constrained environment" (which are all user stories with a worth of 3 story points).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\nDeveloper id like separate real repository coupling test infrastructure easy test thin layer" is a user story, and is worth 8 story points. This was predicted because it is most similar to: \n Developer id like fix offset management source module efficiently perform fetch operation given and similar to "Continuation would like investigate spark develop poc identify best appropriate design implementation" and similar to "Developer id like setup performance testing infrastructure start benching continue" (which are all user stories with a worth of 8 story points).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\nDeveloper id like setup ci infrastructure build project continuously every" is a user story, and is worth 5 story points. This was predicted because it is most similar to: \n Developer id like configure environment variable implement kerberos would need additional work and similar to "User id like capability ingest based batch enhanced performance throughput example http log" and similar to "Developer id like create persistent repository streams could leverage metadata streaming pipe failure" (which are all user stories with a worth of 5 story points).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\nNeed set small commit level acceptance default commit level jobs original sporadically fail need set small value" is a user story, and is worth 3 story points. This was predicted because it is most similar to: \n Developer id like isolate different project dirt project doesnt depend upon thus incorrect cp file generation eclipse and similar to "Developer id like option source module consume data bandwidth efficient protocol fits constrained environment" and similar to "User id like option sink use provide better resiliency case willing accept performance penalty choose option" (which are all user stories with a worth of 3 story points).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\n"The input text was refused as it is not a user story. This was determined because Ui add pagination page add pagination page" was most similar to:\n"Update spring framework dependency ga" and similar to "Create integration test" and similar to "Shell - job parameter true default currently shell parameter default false true consequence parameter currently work" (which are not user stories).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\nDeveloper id like measure baseline serialization determine performance" is a user story, and is worth 3 story points. This was predicted because it is most similar to: \n Developer id like create public counter pipe demonstrate development experience and similar to "Developer id like create tuple use measure tuple based performance" and similar to "User id like option sink use provide better resiliency case willing accept performance penalty choose option" (which are all user stories with a worth of 3 story points).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\nSource add support tcp source currently hard-coded use udp port need port provide option use tcp" is a user story, and is worth 5 story points. This was predicted because it is most similar to: \n User id like capability ingest based batch enhanced performance throughput example http log and similar to "Developer id like create persistent repository streams could leverage metadata streaming pipe failure" and similar to "User id like option sink perform indexing search server" (which are all user stories with a worth of 5 story points).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\n XUSP could not provide an answer as the amount of similarity between Create aggregate counter aggregate counter discrete time poc implementation java based library good description desired feature set"\nand "Jdbc sink broken - looks like got booted jdbc sink broken simple time jdbc bad sql grammar insert test exception user privilege object found test looks like got" does not exceed the minimum threshold of 75%.',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\nDeveloper id like add load generator source module could use performance testing" is a user story, and is worth 8 story points. This was predicted because it is most similar to: \n User id like option write file roll sink store local file system and similar to "Continuation would like investigate spark develop poc identify best appropriate design implementation" and similar to "Developer id like fix offset management source module efficiently perform fetch operation given" (which are all user stories with a worth of 8 story points).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\n"The input text was refused as it is not a user story. This was determined because Support delete taps" was most similar to:\n"Update reactor m3" and similar to "Documentation" and similar to "Shell integration yarn provide better shell integration run yarn yarn kill tab completion yarn submit like app name yarn list filter app etc admin server tab completion running yarn" (which are not user stories).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\n XUSP could not provide an answer as the amount of similarity between Job container needs access needs content exposed via tcp network service container access update status job run property host port admin accessible user one default testing - unit - bring module admin verify default host port work verify container different machine access admin"\nand "Create based module copy file spring batch great complex want create simple processor fs groovy would nice code code goal script use stream like script file byte byte enhanced sink thats binary data like might elegant would work script spring even didnt sure - stdin put would work hoped" does not exceed the minimum threshold of 75%.',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\n"The input text was refused as it is not a user story. This was determined because Sink module" was most similar to:\n"Update reactor m3" and similar to "Documentation" and similar to "Shell integration yarn provide better shell integration run yarn yarn kill tab completion yarn submit like app name yarn list filter app etc admin server tab completion running yarn" (which are not user stories).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\n"The input text was refused as it is not a user story. This was determined because Follow experiment removal list branch" was most similar to:\n"Create integration test framework add top level utility methods manage deploy start stop methods used underlying integration control test environment" and similar to "Jdbc sink table jdbc sink table single column one even file" and similar to "Fix among shell integration looks like application used shell integration test class test classes well common need avoid" (which are not user stories).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\n"The input text was refused as it is not a user story. This was determined because Add global http interceptor order centralize error logging theoretically would centralize logging global substantially - see limitation" was most similar to:\n"Update filter json value filter section use shell instead curl see" and similar to "Documentation jms source jms added list also corresponding section basic usage" and similar to "Fix among shell integration looks like application used shell integration test class test classes well common need avoid" (which are not user stories).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\nDeveloper id like upgrade release lattice demonstrate data flow latest lattice" is a user story, and is worth 1 story points. This was predicted because it is most similar to: \n User streams duplicate name id expect streams unique time and similar to "Developer id like get rid" and similar to "Spring user would like able create new stream ui flow shown graphical way also definition tab right doesnt happen due javascript error code function bound update function code" (which are all user stories with a worth of 1 story points).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\n XUSP could not provide an answer as the amount of similarity between User trying compose job one definition however getting following error message could code create successfully job create foo successfully job foo create command could find module name type job code"\nand "Performance tester id like rerun baseline rabbit compare previous performance note - true - default could also vary default size compute record granular level" does not exceed the minimum threshold of 75%.',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\nSpring developer id like move module use sink build streaming pipeline" is a user story, and is worth 2 story points. This was predicted because it is most similar to: \n Spring developer id like move jdbc module use source build streaming pipeline and similar to "Spring developer id like port filter module use processor module build streaming pipeline" and similar to "Developer id like port module use sink module build streaming pipeline" (which are all user stories with a worth of 2 story points).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\nPrediction:\nDeveloper id like add support explicit partition count configuration use option cleverly route intended consumer module" is a user story, and is worth 5 story points. This was predicted because it is most similar to: \n User id like capability ingest based batch enhanced performance throughput example http log and similar to "User id like access evaluate current state respectively identify capture stream logging mechanism" and similar to "Developer id like configure environment variable implement kerberos would need additional work" (which are all user stories with a worth of 5 story points).',
        'XUSP is an algorithm that is designed to automatically determine the amount of story points for a given user story.\nThe prediction of the story point value is made using a specific process called xDNN.\nxDNN classifies items based on the similarity between it and already learned items.\n XUSP could not provide an answer as the amount of similarity between Support listing shell pair functionality module list would list table format module list would list source"\nand "Conversion sample exception dependency use snapshot even m5 conversion exception attached" does not exceed the minimum threshold of 75%.']

    explanandum_aspects = ['my:amount', 'my:feature', 'my:prediction', 'my:user_story', 'my:story_point',
                           'my:specific_process', 'my:to_automatcally_determine_amount_of_story_point_for_user_story']

    kwargs = {"explanandum_aspects": explanandum_aspects,
              "cases": cases}

    dox_algo = DoxAlgorithmAdapter()
    dox_algo.run(callback=temp_callback, **kwargs)
